version: '3.3'

services:
  server:
    image: card-game-server:dev
    build:
      context: ./packages/server/
      target: dev
    volumes:
      - ./packages/server/:/app
    ports:
      - ${SERVER_PORT:-5500}:3000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: main
      DB_PASSWORD: main
      DB_DATABASE: card_game
      JWT_SECRET: 123

  client:
    image: card-game-client:dev
    build:
      context: ./packages/client/
      target: dev
    volumes:
      - ./packages/client/:/app
    ports:
      - ${CLIENT_PORT:-3000}:3000
    environment:
      - REACT_APP_SERVER_URL=http://localhost:${SERVER_PORT:-5500}

  admin:
    image: card-game-admin:dev
    build:
      context: ./packages/admin/
      target: dev
    volumes:
      - ./packages/admin/:/app
    ports:
      - ${ADMIN_PORT:-3003}:3003
    environment:
      - PORT=3003
      - REACT_APP_SERVER_URL=http://localhost:${SERVER_PORT:-5500}

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: main
      MYSQL_PASSWORD: main
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: card_game