version: '3.3'

services:
  server:
    image: card-game-server:staging
    restart: unless-stopped
    build:
      context: ./packages/server/
      target: prod
    ports:
      - ${SERVER_PORT:-5500}:3000
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}

  client:
    image: card-game-client:staging
    restart: unless-stopped
    build:
      context: ./packages/client_v2/
    ports:
      - ${CLIENT_PORT:-3000}:80

  admin:
    image: card-game-admin:staging
    restart: unless-stopped
    build:
      context: ./packages/admin/
      target: prod
      args:
        - SERVER_URL=${SERVER_URL}
    ports:
      - ${ADMIN_PORT:-3003}:80
    environment:
      - REACT_APP_UPLOADCARE_API_KEY=${UPLOADCARE_API_KEY:-eda49b76d2c205c9fbb0}