version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /workspaces/card-game/.gcp/credentials.json
    command: sleep infinity

  server:
    image: node:20
    command: npm run dev
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ../packages/server:/app
      - ../.gcp:/.gcp
    network_mode: service:app
    environment:
      PORT: 5500
      DB_HOST: 0.0.0.0
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
      DB_DATABASE: card_game
      JWT_SECRET: 123
      GOOGLE_APPLICATION_CREDENTIALS: /.gcp/credentials.json

  client:
    image: node:20
    command: npm start
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ../packages/client:/app
    network_mode: service:app

  admin:
    image: node:20
    command: npm start
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ../packages/admin:/app
    network_mode: service:app
    environment:
      PORT: 3001
      REACT_APP_SERVER_URL: http://localhost:${SERVER_PORT:-5500}
      REACT_APP_UPLOADCARE_API_KEY: 94946bce4985d9873f34

  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    network_mode: service:app
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: card_game
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

volumes:
  db:
