version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /workspaces/card-game/.gcp/credentials.json
    command: sleep infinity

  server:
    image: node:20
    command: npm run dev
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ../packages/server:/app
      - ../.gcp:/.gcp
    network_mode: service:app
    environment:
      PORT: 5500
      DB_URI: mongodb://root:root@mongo:27017/card_game?authSource=admin
      JWT_SECRET: 123
      GOOGLE_APPLICATION_CREDENTIALS: /.gcp/credentials.json

  client:
    image: node:20
    command: npm start
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ../packages/client:/app
    network_mode: service:app

  admin:
    image: node:20
    command: npm start
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ../packages/admin:/app
    network_mode: service:app
    environment:
      PORT: 3001
      REACT_APP_SERVER_URL: http://localhost:${SERVER_PORT:-5500}
      REACT_APP_UPLOADCARE_API_KEY: 94946bce4985d9873f34

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: card_game

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

volumes:
  db:
