name: Client

on:
  push:
    branches:
      - main

jobs:
  build:
    run_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd packages/client_v2
          npm ci
          npm build
        shell: basg